language: nix

dist: xenial

script:
  - nix build --out-link miniserver.img
  - systemd-nspawn --image miniserver.img --ephemeral -- /usr/bin/nginx -V

after_success:
  # List output to confirm reproducibilty.
  - sha256sum miniserver.img

notifications:
  email: false
