name: "Build"

on: "push"

jobs:
  build:
    runs-on: "ubuntu-18.04"
    steps:
      - uses: "actions/checkout@v2"

      - uses: "cachix/install-nix-action@v12"
        with:
          nix_path: "nixpkgs=channel:nixos-unstable"

      - name: "Install build dependencies"
        run: "sudo apt install systemd-container"

      - name: "Build"
        run: "nix build --out-link miniserver.img"

      - name: "Print reproducibility metadata"
        run: "sha256sum miniserver.img"

      - name: "Dry-run Nginx"
        run: "sudo systemd-nspawn --image miniserver.img --ephemeral -- /usr/bin/nginx -V"

      - uses: "actions/upload-artifact@v2"
        with:
          name: "miniserver.img"
          path: "miniserver.img"
