name: "Build"

on: "push"

jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@v2"

      - uses: "cachix/install-nix-action@v18"
        with:
          nix_path: "nixpkgs=channel:nixos-unstable"
          install_url: "https://releases.nixos.org/nix/nix-2.11.1/install"

      - name: "Install build dependencies"
        run: "sudo apt install systemd-container"

      - name: "Build"
        # Also cp the result out of the out directory, because the
        # upload-artifact action apparently does not like symlinks.
        run: "nix build -f default.nix --out-link out\ncp out/miniserver.img ."

      - name: "Print reproducibility metadata"
        run: "sha256sum out/*"

      - name: "Dry-run Nginx"
        run: "sudo systemd-nspawn --image out/miniserver.img --ephemeral -- /usr/bin/nginx -V"

      - uses: "actions/upload-artifact@v2"
        with:
          name: "miniserver.img"
          path: "miniserver.img"
